# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Announcements', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousel'},
        ),
        migrations.AlterModelOptions(
            name='latestsermons',
            options={'verbose_name': 'Latest Sermon', 'verbose_name_plural': 'Latest Sermons'},
        ),
        migrations.AlterModelOptions(
            name='mainevent',
            options={'verbose_name': 'Main Event', 'verbose_name_plural': 'Main Event'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
    ]
