# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0002_auto_20170902_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
