# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0004_auto_20170902_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('fullverse', models.TextField(max_length=500)),
                ('versenumber', models.CharField(max_length=50)),
            ],
        ),
    ]
