# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0005_tenets_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenets',
            options={'verbose_name': 'Tenet', 'verbose_name_plural': 'Tenets'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Theme'},
        ),
    ]
