# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0006_auto_20170902_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenets',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
