# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0007_auto_20170902_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenets',
        ),
    ]
