# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0008_delete_tenets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutivesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutivesThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='executivesdetails',
            name='executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newwine.ExecutivesThumbnail'),
        ),
    ]
