# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0009_auto_20170903_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('album_pic', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Photo Album',
                'verbose_name_plural': 'Photo Albums',
            },
        ),
        migrations.AlterModelOptions(
            name='executivesdetails',
            options={'verbose_name': 'Executives Details', 'verbose_name_plural': 'Executives Details'},
        ),
        migrations.AlterModelOptions(
            name='executivesthumbnail',
            options={'verbose_name': 'Executives Thumbnails', 'verbose_name_plural': 'Executives Thumbnails'},
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newwine.PhotoAlbum'),
        ),
    ]
