# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0010_auto_20170904_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
