# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0012_registeredmembers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredmembers',
            options={'verbose_name': 'Registered Members', 'verbose_name_plural': 'Registered Members'},
        ),
        migrations.AlterField(
            model_name='registeredmembers',
            name='other_names',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
