# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0013_auto_20170907_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredmembers',
            name='other_names',
        ),
    ]
