# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0014_remove_registeredmembers_other_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_image', models.FileField(upload_to='')),
                ('department_name', models.CharField(max_length=100)),
                ('department_about', models.TextField(max_length=1000)),
                ('department_function', models.TextField(max_length=1000)),
                ('department_meeting_day_1', models.CharField(max_length=50)),
                ('department_meeting_day_2', models.CharField(max_length=50)),
                ('department_meeting_time_1', models.CharField(max_length=50)),
                ('department_meeting_time_2', models.CharField(max_length=50)),
                ('department_venue_1', models.CharField(max_length=50)),
                ('department_venue_2', models.CharField(max_length=50)),
                ('department_leader_name', models.CharField(max_length=150)),
                ('department_leader_hostel', models.CharField(max_length=100)),
                ('department_leader_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
