# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0015_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='departments',
            name='department_leader_image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
