# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0016_auto_20171111_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_leader_image',
            field=models.FileField(upload_to=''),
        ),
    ]
