# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0017_auto_20171111_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=150)),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
    ]
