# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0018_sermons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermons',
            options={'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AddField(
            model_name='sermons',
            name='day_of_message',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
