# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0019_auto_20171116_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cov_img', models.FileField(upload_to='')),
                ('cov_name', models.CharField(max_length=150)),
                ('cov_day', models.CharField(max_length=20)),
                ('cov_time', models.CharField(max_length=10)),
                ('cov_location', models.CharField(max_length=60)),
                ('cov_head', models.CharField(max_length=200)),
                ('cov_contact', models.CharField(max_length=20)),
                ('dept_cov_head', models.CharField(max_length=200)),
                ('dept_cov_head_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
