# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0020_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Covenant Family', 'verbose_name_plural': 'Covenant Families'},
        ),
        migrations.AddField(
            model_name='mainevent',
            name='event_time',
            field=models.CharField(default='January 01 1999 00:00:00', max_length=150),
        ),
    ]
