# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0021_auto_20171218_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoAlbum',
            new_name='Gallery',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.RemoveField(
            model_name='images',
            name='album',
        ),
        migrations.RemoveField(
            model_name='images',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='file',
            field=models.FileField(default=1, upload_to='images/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newwine.Gallery'),
        ),
    ]
