# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0022_auto_20171230_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
