# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0023_auto_20171230_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(upload_to='images/', verbose_name='File'),
        ),
    ]
