# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0024_auto_20180101_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newwine.Gallery'),
        ),
    ]
