# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0025_auto_20180101_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermons',
            name='audio',
            field=models.FileField(upload_to='sermons/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='image',
            field=models.FileField(upload_to='sermons/', verbose_name='File'),
        ),
    ]
