# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0026_auto_20180101_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='department_deputy_contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='department_deputy_hostel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='department_deputy_image',
            field=models.FileField(default='', upload_to='leaders/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='department_deputy_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='cov_head_image',
            field=models.FileField(default='', upload_to='leaders/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='dept_head_image',
            field=models.FileField(default='', upload_to='leaders/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_leader_image',
            field=models.FileField(upload_to='leaders/', verbose_name='File'),
        ),
    ]
