# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0027_auto_20180221_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='cov_img',
            field=models.FileField(upload_to='covenant_family/', verbose_name='File'),
        ),
    ]
