# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0028_auto_20180222_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivesthumbnail',
            name='profile',
            field=models.FileField(upload_to='excom/', verbose_name='File'),
        ),
    ]
