# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0030_auto_20180225_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmembers',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
    ]
