# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0031_auto_20180305_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_image',
            field=models.FileField(upload_to='department_image/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='album_pic',
            field=models.FileField(upload_to='album_thumbnails', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.FileField(upload_to='gallery_images/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='mainevent',
            name='image',
            field=models.FileField(upload_to='event/', verbose_name='File'),
        ),
    ]
