# Generated by Django 2.0.7 on 2018-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0032_auto_20180317_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='newwine.Gallery'),
        ),
    ]
