# Generated by Django 2.0.7 on 2018-07-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0033_auto_20180718_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiators_img', models.FileField(upload_to='initiators_images', verbose_name='File')),
                ('initiators_name', models.CharField(max_length=200)),
                ('initiators_portfolio', models.CharField(max_length=250)),
            ],
        ),
    ]
