# Generated by Django 2.0.7 on 2018-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0034_initiators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiators',
            options={'verbose_name': 'Initiator', 'verbose_name_plural': 'Initiators'},
        ),
        migrations.AddField(
            model_name='departments',
            name='department_deputy_course',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='department_leader_course',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='cov_course',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='cov_hostel',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='dept_cov_course',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='dept_cov_hostel',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
