# Generated by Django 2.0.7 on 2018-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0035_auto_20180719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_deputy_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_leader_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='executivesdetails',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='cov_contact',
            field=models.CharField(max_length=100),
        ),
    ]
