# Generated by Django 2.0.7 on 2018-07-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0036_auto_20180720_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='dept_cov_head_contact',
            field=models.CharField(max_length=150),
        ),
    ]
