# Generated by Django 2.1 on 2018-08-18 00:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0037_auto_20180720_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsermons',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
