# Generated by Django 2.1 on 2018-08-18 04:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0038_auto_20180817_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_img', models.FileField(upload_to='article_images', verbose_name='File')),
                ('article_title', models.CharField(max_length=100)),
                ('article_overview', models.CharField(max_length=200)),
                ('article_body', tinymce.models.HTMLField(verbose_name='Content')),
                ('article_owner_name', models.CharField(max_length=200)),
                ('article_owner_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_portfolio', models.CharField(max_length=200)),
                ('coord_img', models.FileField(upload_to='coordinators', verbose_name='File')),
                ('coord_name', models.CharField(max_length=200)),
                ('coord_course', models.CharField(max_length=200)),
                ('coord_hostel', models.CharField(max_length=200)),
                ('coord_contact', models.CharField(max_length=100)),
                ('coord_role', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_coord_portfolio', models.CharField(max_length=200)),
                ('men_coord_img', models.FileField(upload_to='coordinators', verbose_name='File')),
                ('men_coord_name', models.CharField(max_length=200)),
                ('men_coord_course', models.CharField(max_length=200)),
                ('men_coord_hostel', models.CharField(max_length=200)),
                ('men_coord_contact', models.CharField(max_length=100)),
                ('women_coord_portfolio', models.CharField(max_length=200)),
                ('women_coord_img', models.FileField(upload_to='coordinators', verbose_name='File')),
                ('women_coord_name', models.CharField(max_length=200)),
                ('women_coord_course', models.CharField(max_length=200)),
                ('women_coord_hostel', models.CharField(max_length=200)),
                ('women_coord_contact', models.CharField(max_length=100)),
                ('gender_coord_role', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('team_role', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony_img', models.FileField(upload_to='article_images', verbose_name='File')),
                ('testimony_title', models.CharField(max_length=100)),
                ('testimony_overview', models.CharField(max_length=200)),
                ('testimony_body', tinymce.models.HTMLField(verbose_name='Content')),
                ('testimony_owner_name', models.CharField(max_length=200)),
                ('testimony_owner_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='fullverse',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='versenumber',
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_tenets',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_verse_body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_verse_scripture',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
