# Generated by Django 2.1 on 2018-08-18 20:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0039_auto_20180817_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_img', models.FileField(upload_to='article_images', verbose_name='File')),
                ('note_title', models.CharField(max_length=100)),
                ('note_overview', models.CharField(max_length=200)),
                ('note_body', tinymce.models.HTMLField(verbose_name='Content')),
                ('note_owner_name', models.CharField(max_length=200)),
                ('note_owner_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Church Notes',
                'verbose_name': 'Church Note',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name': 'Coordinator', 'verbose_name_plural': 'Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender Coordinators', 'verbose_name_plural': 'Gender Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='testimonies',
            options={'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
    ]
