# Generated by Django 2.1 on 2018-08-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0040_auto_20180818_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
