# Generated by Django 2.1 on 2018-08-18 20:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0041_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=400, null=True)),
                ('theme_verse_body', tinymce.models.HTMLField(null=True, verbose_name='Content')),
                ('theme_verse_scripture', models.CharField(max_length=150, null=True)),
                ('theme_body', tinymce.models.HTMLField(null=True, verbose_name='Content')),
                ('theme_tenets', tinymce.models.HTMLField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
