# Generated by Django 2.1 on 2018-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0042_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='blog_activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='blog_activity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonies',
            name='blog_activity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
