# Generated by Django 2.1 on 2018-08-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0043_auto_20180819_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='blog_activity',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='blog_activity',
        ),
        migrations.RemoveField(
            model_name='testimonies',
            name='blog_activity',
        ),
    ]
