# Generated by Django 2.1 on 2018-08-19 22:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0044_auto_20180819_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_body',
            field=tinymce.models.HTMLField(verbose_name='Article Body'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='coord_role',
            field=tinymce.models.HTMLField(verbose_name='Coordinator Role'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender_coord_role',
            field=tinymce.models.HTMLField(verbose_name='Gender Coodrinators Role'),
        ),
        migrations.AlterField(
            model_name='latestsermons',
            name='summary',
            field=tinymce.models.HTMLField(verbose_name='Sermon summary'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_body',
            field=tinymce.models.HTMLField(verbose_name='Note Body'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_role',
            field=tinymce.models.HTMLField(verbose_name='Team Role'),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='testimony_body',
            field=tinymce.models.HTMLField(verbose_name='Testimony Body'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Theme Body'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_tenets',
            field=tinymce.models.HTMLField(null=True, verbose_name='Theme Tenets'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_verse_body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Theme Verse Body'),
        ),
    ]
