# Generated by Django 2.1 on 2018-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0045_auto_20180819_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=models.FileField(upload_to='article_images', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_img',
            field=models.FileField(upload_to='article_images', verbose_name='Notes Image'),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='testimony_img',
            field=models.FileField(upload_to='article_images', verbose_name='Testimony Image'),
        ),
    ]
