# Generated by Django 2.1 on 2018-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0046_auto_20180819_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_img',
            field=models.FileField(upload_to='notes_images', verbose_name='Notes Image'),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='testimony_img',
            field=models.FileField(upload_to='testimony_images', verbose_name='Testimony Image'),
        ),
    ]
