# Generated by Django 2.1 on 2018-08-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0047_auto_20180819_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmembers',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registeredmembers',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
