# Generated by Django 2.1 on 2018-08-31 00:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0048_auto_20180830_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_img', models.FileField(upload_to='oultline_images', verbose_name='Study Outline Image')),
                ('outline_title', models.CharField(max_length=100)),
                ('outline_overview', models.CharField(max_length=200)),
                ('outline_body', tinymce.models.HTMLField(verbose_name='Note Body')),
                ('outline_owner_name', models.CharField(max_length=200)),
                ('outline_owner_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Bible Study Outline',
                'verbose_name_plural': 'Bible Study Outlines',
            },
        ),
    ]
