# Generated by Django 2.1.7 on 2019-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newwine', '0049_outlines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Teachings', 'verbose_name_plural': 'Teachings'},
        ),
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.TextField(default='None'),
        ),
    ]
